modules:
  excel_reader: true
  system_builder: true
  optimizer: true
  results_processor: true
  visualizer: true
  analyzer: false
settings:
  solver: cbc
  output_format: xlsx
  create_plots: false
  save_model: false
  debug_mode: false
